version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action/*"
      docker-actions:
        patterns:
          - "docker/*"
