---
extends: default

rules:
  line-length:
    max: 160
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
  comments:
    min-spaces-from-content: 1
  document-start: disable

ignore:
  - .github/workflows/
