---
name: "Self: Release"

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: self-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/shared-release-flow.yml
    with:
      release-type: "simple"
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      RELEASE_GPG_PRIVATE_KEY: ${{ secrets.RELEASE_GPG_PRIVATE_KEY }}
