---
name: "Self: Auto Label"

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: self-auto-label-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  label:
    name: Auto label
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: ./.github/workflows/shared-auto-label.yml
    with:
      type-labels: true
      stack-labels: true
      ensure-labels: true
